# Generated by Django 5.0.14 on 2026-10-01 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('tipo_camion', models.CharField(blank=True, max_length=50, null=True)),
                ('es_externo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('POZO', 'Pozo Descarga'), ('PRENSA', 'Prensa'), ('CUBA', 'Cuba')], max_length=50)),
                ('ala', models.CharField(choices=[('IZQ', 'Ala Izquierda'), ('DER', 'Ala Derecha'), ('N/A', 'No Aplica')], default='N/A', max_length=50)),
                ('cap_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cap_minima', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esta_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaVendimia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctto_contrato', models.CharField(max_length=100)),
                ('productor', models.CharField(max_length=200)),
                ('fundo', models.CharField(max_length=200)),
                ('variedad', models.CharField(max_length=100)),
                ('kilos_programados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_programada', models.DateField()),
                ('grupo_mezcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupomezcla')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(choices=[('TRANSITO', 'En Tránsito'), ('ROMANA', 'En Romana'), ('PATIO', 'En Patio (Esperando)'), ('DESCARGANDO', 'Descargando'), ('FINALIZADO', 'Finalizado')], default='TRANSITO', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camion')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programavendimia')),
            ],
        ),
        migrations.CreateModel(
            name='PesajeRomana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_neto_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_llegada_real', models.DateTimeField()),
                ('payload_original', models.JSONField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='EventoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta_proyectado', models.DateTimeField()),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('payload_original', models.JSONField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionGantt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('override_manual', models.BooleanField(default=False)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instalacion')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viaje')),
            ],
        ),
    ]
