# Generated by Django 5.0.14 on 2026-10-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_mezcla', models.CharField(max_length=100)),
                ('volumen_litros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instalacion')),
            ],
        ),
    ]
