# Generated by Django 5.0.14 on 2026-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventariobodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloj_virtual', models.DateTimeField()),
            ],
            options={
                'db_table': 'simulacion_state',
            },
        ),
    ]
