# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_simulacionstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventogps',
            name='hora_aviso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignaciongantt',
            name='es_tentativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado_actual',
            field=models.CharField(
                choices=[
                    ('TRANSITO', 'En Tránsito'),
                    ('ROMANA', 'En Romana'),
                    ('PATIO', 'En Patio (Esperando)'),
                    ('DESCARGANDO', 'Descargando'),
                    ('FINALIZADO', 'Finalizado'),
                    ('ALERTA_ATRASO', 'Alerta: Atraso Crítico'),
                ],
                default='TRANSITO',
                max_length=50,
            ),
        ),
    ]
