# Generated by Django 5.0.14 on 2026-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dss_patio_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_evento', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'evento_simulacion',
                'ordering': ['hora_evento'],
            },
        ),
    ]
